app:
  name: industrial_discovery
  env: dev

server:
  host: 0.0.0.0
  port: 9300

qwen:
  openai_base_url: http://127.0.0.1:9314/v1
  model: Qwen2.5-7B-Instruct
  api_key: sk-local-anything

mongodb:
  uri: mongodb://localhost:27017
  db: industrial_discovery

qdrant:
  url: http://localhost:6333
  collection: industrial_chunks

crawler:
  user_agent: IndustrialDiscovery/1.0
  timeout: 30
  max_depth: 3
